//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLIBRARY.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LIBRARYDBEntities : DbContext
    {
        public LIBRARYDBEntities()
            : base("name=LIBRARYDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_ABOUT> TBL_ABOUT { get; set; }
        public virtual DbSet<TBL_AUTHOR> TBL_AUTHOR { get; set; }
        public virtual DbSet<TBL_BOOK> TBL_BOOK { get; set; }
        public virtual DbSet<TBL_CATEGORY> TBL_CATEGORY { get; set; }
        public virtual DbSet<TBL_CONTACT> TBL_CONTACT { get; set; }
        public virtual DbSet<TBL_DEPOSIT> TBL_DEPOSIT { get; set; }
        public virtual DbSet<TBL_EMPLOYEE> TBL_EMPLOYEE { get; set; }
        public virtual DbSet<TBL_LANGUAGE> TBL_LANGUAGE { get; set; }
        public virtual DbSet<TBL_LIBRARY> TBL_LIBRARY { get; set; }
        public virtual DbSet<TBL_PUBLISHER> TBL_PUBLISHER { get; set; }
        public virtual DbSet<TBL_USER> TBL_USER { get; set; }
        public virtual DbSet<TBL_TILL> TBL_TILL { get; set; }
        public virtual DbSet<TBL_PUNISHMENT> TBL_PUNISHMENT { get; set; }
        public virtual DbSet<TBL_MESSAGES> TBL_MESSAGES { get; set; }
        public virtual DbSet<TBL_NOTIFICATION> TBL_NOTIFICATION { get; set; }
        public virtual DbSet<TBL_ADMİN> TBL_ADMİN { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> ENFAZLAKITAPYAZAR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ENFAZLAKITAPYAZAR");
        }
    
        public virtual ObjectResult<ENIYIYAYINEVI_Result> ENIYIYAYINEVI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ENIYIYAYINEVI_Result>("ENIYIYAYINEVI");
        }
    
        public virtual ObjectResult<ENBASARILIPERSONEL_Result> ENBASARILIPERSONEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ENBASARILIPERSONEL_Result>("ENBASARILIPERSONEL");
        }
    
        public virtual ObjectResult<BUGUNKUEMANETLER_Result> BUGUNKUEMANETLER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BUGUNKUEMANETLER_Result>("BUGUNKUEMANETLER");
        }
    
        public virtual ObjectResult<string> ENCOKOKUNANKITAP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ENCOKOKUNANKITAP");
        }
    
        public virtual ObjectResult<string> ENAKTIFUYE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ENAKTIFUYE");
        }
    
        public virtual ObjectResult<Nullable<int>> BUGUNKU_EMANETLER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BUGUNKU_EMANETLER");
        }
    
        public virtual ObjectResult<string> EN_IYI_YAYINEVI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EN_IYI_YAYINEVI");
        }
    }
}
