//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLIBRARY.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PUNISHMENT
    {
        public int ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> DEPOSITID { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual TBL_DEPOSIT TBL_DEPOSIT { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
