//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLIBRARY.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEPOSIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DEPOSIT()
        {
            this.TBL_PUNISHMENT = new HashSet<TBL_PUNISHMENT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BOOKID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<int> LIBRARYID { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<System.DateTime> USERGETTIME { get; set; }
        public Nullable<bool> TRANSACTIONSTATUS { get; set; }
    
        public virtual TBL_BOOK TBL_BOOK { get; set; }
        public virtual TBL_EMPLOYEE TBL_EMPLOYEE { get; set; }
        public virtual TBL_LIBRARY TBL_LIBRARY { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PUNISHMENT> TBL_PUNISHMENT { get; set; }
    }
}
