//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLIBRARY.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_USER()
        {
            this.TBL_DEPOSIT = new HashSet<TBL_DEPOSIT>();
            this.TBL_PUNISHMENT = new HashSet<TBL_PUNISHMENT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string MAIL { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string PHOTOGRAPH { get; set; }
        public string TELEPHONENUM { get; set; }
        public string SCHOOL { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DEPOSIT> TBL_DEPOSIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PUNISHMENT> TBL_PUNISHMENT { get; set; }
    }
}
