
--BU TRÝGGERIN ADI CEZAMÝKTAR OLACAK--
ALTER TRIGGER CEZAMIKTAR 

--BU TRÝGGER TBL_DEPOSÝTTEN VERÝLERÝ ALACAK--
ON TBL_DEPOSIT

--BU TRÝGGER HER TBL_DEPOSIT GÜNCELLENDÝKTEN SONRA ÇALIÞACAK--
AFTER UPDATE 
AS

--BU TRIGGER IN 2 ADET YEREL DEÐÝÞKENÝ OLACAK. @UYE VE @HAREKET
DECLARE @UYE int 
DECLARE @HAREKET int
DECLARE @ENDTIME date


--BU TRIGGERIN YEREL DEÐÝÞKENLERÝNDEN @UYE HAREKET TABLOSUNDAKÝ ÜYEÝD VE @HAREKET HAREKET TABLOSUNDAKÝ ÝD DEÐERÝNE SAHÝP OLACAK.
SELECT @UYE=USERID  , @HAREKET=ID, @ENDTIME=USERGETTIME  FROM inserted  --ATAMALARI YAPTIM--


--OLUÞTURDUÐUMUZ @UYE VE @HAREKET DEÐÝÞKENLERÝNÝN DEÐERLERÝNÝ CEZA TABLOMUZDAKÝ ÜYEÝD VE HAREKETÝD SÜTUNLARINA ATAYACAÐIZ.
--TUTAR ÝÇÝN DEÐÝÞKEN OLUÞTURMADIK.
--TUTARI ÝADE TARÝHÝ VE GETÝRÝLEN TARÝH ARASINDAKÝ FARKIN DAY FORMATINA ÇEVRÝLMESÝ ÝLE HESAPLADIK. BU DEÐERÝ HAREKETTEKÝ TUTAR SÜTUNUNA ATAYACAÐIZ. 
INSERT INTO TBL_PUNISHMENT(USERID,DEPOSITID,PRICE,STARTTIME,ENDTIME) VALUES (@UYE,@HAREKET,(SELECT DATEDIFF(DAY,ENDTIME,USERGETTIME)FROM TBL_DEPOSIT WHERE ID=@HAREKET),(SELECT DATEADD(DAY,1,ENDTIME) FROM TBL_DEPOSIT WHERE ID=@HAREKET) ,@ENDTIME )

--NOT: DATEDIFF IN GOREVI 2 TARIH ARASINDAKÝ FARKI ÝSTENEN FORMATTA GETÝRMEKTÝR. ÖRN BÝZ DAY TÜRÜNDE ÝSTEDÝÐÝMÝZ ÝÇÝN DAY TÜRÜNDE GELDÝ. 

