CREATE TRIGGER KITAPDURUM
ON TBL_DEPOSIT
AFTER INSERT
AS
DECLARE @KITAP INT
SELECT @KITAP=BOOKID FROM inserted --hareket tablomuza eklenen kayýttaki BOOKID deðerini @KÝTAP DEGERÝNE ATADIK.
UPDATE TBL_BOOK SET STATUS=0 WHERE ID=@KITAP